# Generated by Django 6.0.4 on 2026-04-28 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="location",
        ),
        migrations.DeleteModel(
            name="Locations",
        ),
    ]
