# Generated by Django 6.0.4 on 2026-04-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_locations_alter_employee_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employment_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="joining_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
