# Generated by Django 6.0.4 on 2026-04-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0004_alter_employee_employee_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="location",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Locations",
        ),
    ]
